language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

script:
  - pytest --cov=babs

after_success:
  - codecov
